#!/usr/bin/env bash
set -euo pipefail

# Smoke test for CLI-friendly API endpoints:
# - spins up anvil
# - deploys GHBounties with a non-zero payoutAuthorizer
# - migrates sqlite db
# - starts the API
# - hits a few endpoints that don't require real GitHub credentials
#
# Optional (for full device-flow test):
# - set GITHUB_OAUTH_CLIENT_ID to a real GitHub OAuth app client id
#
# NOTE: This script intentionally avoids requiring a GitHub token with admin/PR-author permissions.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"
API_URL="${API_URL:-}"
API_PORT="${API_PORT:-}"
CHAIN_ID="${CHAIN_ID:-31337}"
DATABASE_URL="${DATABASE_URL:-file:./prisma/dev.db}"

# Required env (this script intentionally does not read repo `.env`):
# - DEPLOYER_PRIVATE_KEY: funded private key used to broadcast the deploy txs (e.g. anvil account #0).
#
# Optional env:
# - BACKEND_SIGNER_PRIVATE_KEY: 32-byte hex private key used by the API to sign EIP-712 payloads, and by
#   the deploy script to set a non-zero payoutAuthorizer.
# - PAYOUT_AUTHORIZER: payout authorizer address (alternative to BACKEND_SIGNER_PRIVATE_KEY).

# Derive defaults / parse port.
if [[ -z "${API_PORT}" ]]; then
  if [[ -n "${API_URL}" && "${API_URL}" =~ ^https?://[^/]+:([0-9]+) ]]; then
    API_PORT="${BASH_REMATCH[1]}"
  else
    API_PORT="8787"
  fi
fi
if [[ -z "${API_URL}" ]]; then
  API_URL="http://127.0.0.1:${API_PORT}"
fi

DEPLOYER_PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY:-${PRIVATE_KEY:-}}"
if [[ -z "${DEPLOYER_PRIVATE_KEY}" ]]; then
  echo "Missing DEPLOYER_PRIVATE_KEY (or PRIVATE_KEY)." >&2
  echo "Set it to a funded account private key (e.g. anvil account #0) to broadcast deploy transactions." >&2
  exit 1
fi

PAYOUT_AUTHORIZER="${PAYOUT_AUTHORIZER:-}"

# Backend signer key used by the API to sign EIP-712 payloads.
# Any 32-byte hex is fine for local test; do not commit real keys.
BACKEND_SIGNER_PRIVATE_KEY="${BACKEND_SIGNER_PRIVATE_KEY:-}"
if [[ -z "${BACKEND_SIGNER_PRIVATE_KEY}" && -z "${PAYOUT_AUTHORIZER}" ]]; then
  echo "Missing BACKEND_SIGNER_PRIVATE_KEY (preferred) or PAYOUT_AUTHORIZER." >&2
  echo "Set BACKEND_SIGNER_PRIVATE_KEY=0x... (32-byte hex) to enable signing + set a non-zero payoutAuthorizer." >&2
  echo "Or set PAYOUT_AUTHORIZER=0x... (address) to deploy with a non-zero payoutAuthorizer without signing enabled." >&2
  exit 1
fi

# Encryption key required for device flow sessions (Option 2). Autogenerated if unset.
API_TOKEN_ENCRYPTION_KEY="${API_TOKEN_ENCRYPTION_KEY:-}"
if [[ -z "${API_TOKEN_ENCRYPTION_KEY}" ]]; then
  API_TOKEN_ENCRYPTION_KEY="$(openssl rand -hex 32)"
fi

ANVIL_LOG="${ANVIL_LOG:-/tmp/ghb_anvil.log}"
API_LOG="${API_LOG:-/tmp/ghb_api.log}"

cleanup() {
  if [[ -n "${API_PID:-}" ]]; then
    kill "${API_PID}" >/dev/null 2>&1 || true
  fi
  if [[ -n "${ANVIL_PID:-}" ]]; then
    kill "${ANVIL_PID}" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

echo "Starting anvil..."
anvil --host 127.0.0.1 --port 8545 >"${ANVIL_LOG}" 2>&1 &
ANVIL_PID=$!

echo "Waiting for RPC..."
for i in {1..80}; do
  if curl -s -X POST "${RPC_URL}" -H "content-type: application/json" --data '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' | jq -e '.result' >/dev/null; then
    break
  fi
  sleep 0.1
  if [[ "${i}" -eq 80 ]]; then
    echo "RPC did not start" >&2
    tail -n 50 "${ANVIL_LOG}" >&2 || true
    exit 1
  fi
done

echo "Deploying contract..."
deploy_env=(RPC_URL="${RPC_URL}" PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY}")
if [[ -n "${BACKEND_SIGNER_PRIVATE_KEY}" ]]; then
  deploy_env+=(BACKEND_SIGNER_PRIVATE_KEY="${BACKEND_SIGNER_PRIVATE_KEY}")
fi
if [[ -n "${PAYOUT_AUTHORIZER}" ]]; then
  deploy_env+=(PAYOUT_AUTHORIZER="${PAYOUT_AUTHORIZER}")
fi
CONTRACT_ADDRESS="$(
  env "${deploy_env[@]}" bash "${ROOT_DIR}/scripts/deploy.sh"
)"
echo "CONTRACT_ADDRESS=${CONTRACT_ADDRESS}"

echo "Running prisma migrations..."
(
  cd "${ROOT_DIR}/apps/api"
  DATABASE_URL="${DATABASE_URL}" pnpm exec prisma migrate deploy >/dev/null
)

echo "Starting API..."
(
  cd "${ROOT_DIR}/apps/api"
  export DOTENV_CONFIG_PATH=/dev/null
  export DATABASE_URL="${DATABASE_URL}"
  export RPC_URL="${RPC_URL}"
  export CHAIN_ID="${CHAIN_ID}"
  export CONTRACT_ADDRESS="${CONTRACT_ADDRESS}"
  if [[ -n "${BACKEND_SIGNER_PRIVATE_KEY}" ]]; then
    export BACKEND_SIGNER_PRIVATE_KEY="${BACKEND_SIGNER_PRIVATE_KEY}"
  fi
  export API_TOKEN_ENCRYPTION_KEY="${API_TOKEN_ENCRYPTION_KEY}"
  export PORT="${API_PORT}"
  pnpm exec tsx src/index.ts
) >"${API_LOG}" 2>&1 &
API_PID=$!

echo "Waiting for API /health..."
for i in {1..120}; do
  if curl -s "${API_URL}/health" | jq -e '.ok==true' >/dev/null; then
    break
  fi
  sleep 0.1
  if [[ "${i}" -eq 120 ]]; then
    echo "API did not become healthy" >&2
    tail -n 80 "${API_LOG}" >&2 || true
    exit 1
  fi
done

echo
echo "GET /contract"
curl -s "${API_URL}/contract" | jq '{chainId,contractAddress,payoutAuthorizer,dao,daoDelaySeconds,defaultLockDuration}'

echo
echo "GET /id"
curl -s "${API_URL}/id?repo=octocat/Hello-World&issue=1" | jq '{repo,repoHash,issueNumber,bountyId}'

echo
echo "POST /payout-auth (expect 401 without auth)"
curl -s -o /tmp/ghb_payout_auth.json -w "%{http_code}\n" -X POST "${API_URL}/payout-auth" -H "Content-Type: application/json" -d '{}' || true
cat /tmp/ghb_payout_auth.json | jq || true

echo
echo "POST /claim-auth (expect 401 without auth)"
curl -s -o /tmp/ghb_claim_auth.json -w "%{http_code}\n" -X POST "${API_URL}/claim-auth" -H "Content-Type: application/json" -d '{}' || true
cat /tmp/ghb_claim_auth.json | jq || true

echo
echo "POST /refund-auth (expect 401 without auth)"
curl -s -o /tmp/ghb_refund_auth.json -w "%{http_code}\n" -X POST "${API_URL}/refund-auth" -H "Content-Type: application/json" -d '{}' || true
cat /tmp/ghb_refund_auth.json | jq || true

echo
if [[ -n "${GITHUB_OAUTH_CLIENT_ID:-}" ]]; then
  echo "POST /auth/device/start (should return device codes)"
  curl -s "${API_URL}/auth/device/start" -H "Content-Type: application/json" -d '{}' | jq '{userCode,verificationUri,interval,expiresIn}'
else
  echo "Skipping device-flow success test (set GITHUB_OAUTH_CLIENT_ID to enable)."
  echo "POST /auth/device/start (expect 500 missing GITHUB_OAUTH_CLIENT_ID)"
  curl -s -o /tmp/ghb_device_start.json -w "%{http_code}\n" -X POST "${API_URL}/auth/device/start" -H "Content-Type: application/json" -d '{}' || true
  cat /tmp/ghb_device_start.json | jq || true
fi

echo
echo "Smoke test OK."
